# try
The above shows the use of try and catch fuction by doing normal devision in c++.
